
services:


  primes-service-database-postgres:
    image: postgres:alpine
    container_name: primes-database
    ports:
      - "5001:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primes

  primes-service:
    image: primes-service
    build:
      context: /Users/tarashbudhrani/Downloads/gateway-service
      dockerfile: Dockerfile
    container_name: primes-service
    ports:
      - "4001:8080"
    environment:
      - server.port=8080
      - spring.datasource.url=jdbc:postgresql://primes-database:5432/primes
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.rabbitmq.host=localhost
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
    restart: "no"
    depends_on:
      - primes-service-database-postgres



  gateway-service:
    image: gateway-service
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      - SERVER_PORT=8180
      - SPRING_APPLICATION_JSON={"server.max-http-request-header-size":"32KB"}
    ports:
      - "4000:8180"
    depends_on:
      - primes-service
